apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop-web
  namespace: petshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petshop-web
  template:
    metadata:
      labels:
        app: petshop-web
    spec:
      containers:
        - name: petshop-web
          image: <ACR_LOGIN_SERVER>/petshop:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

